export interface Skill {
  id: string;
  name: string;
  checked: boolean;
}

export interface SkillsCategories {
  [key: string]: Skill[];
}

export const INITIAL_SKILLS_CATEGORIES: SkillsCategories = {
  programmingLanguages: [
    { id: "c", name: "C", checked: false },
    { id: "cpp", name: "C++", checked: false },
    { id: "csharp", name: "C#", checked: false },
    { id: "go", name: "Go", checked: false },
    { id: "java", name: "Java", checked: false },
    { id: "js", name: "JS", checked: false },
    { id: "ts", name: "TS", checked: false },
    { id: "php", name: "PHP", checked: false },
    { id: "python", name: "Python", checked: false },
    { id: "ruby", name: "Ruby", checked: false },
    { id: "rust", name: "Rust", checked: false },
    { id: "scala", name: "Scala", checked: false },
    { id: "kotlin", name: "Kotlin", checked: false },
    { id: "erlang", name: "Erlang", checked: false },
    { id: "coffeescript", name: "CoffeeScript", checked: false },
    { id: "elixir", name: "Elixir", checked: false },
    { id: "dart", name: "Dart", checked: false },
    { id: "r", name: "R", checked: false },
    { id: "swift", name: "Swift", checked: false },
    { id: "objectivec", name: "Objective-C", checked: false },
    { id: "perl", name: "Perl", checked: false },
  ],
  frontendDevelopment: [
    { id: "vue", name: "Vue.js", checked: false },
    { id: "react", name: "React", checked: false },
    { id: "svelte", name: "Svelte", checked: false },
    { id: "angular", name: "Angular", checked: false },
    { id: "ember", name: "Ember", checked: false },
    { id: "backbone", name: "Backbone", checked: false },
    { id: "bootstrap", name: "Bootstrap", checked: false },
    { id: "css", name: "CSS", checked: false },
    { id: "html", name: "HTML", checked: false },
    { id: "pug", name: "Pug", checked: false },
    { id: "sass", name: "Sass", checked: false },
    { id: "less", name: "Less", checked: false },
    { id: "webcomponents", name: "Web Components", checked: false },
    { id: "babel", name: "Babel", checked: false },
    { id: "qt", name: "Qt", checked: false },
    { id: "d3", name: "D3.js", checked: false },
    { id: "lit", name: "Lit", checked: false },
    { id: "preact", name: "Preact", checked: false },
    { id: "stencil", name: "Stencil", checked: false },
    { id: "materialui", name: "Material-UI", checked: false },
    { id: "tailwindcss", name: "Tailwind CSS", checked: false },
    { id: "bulma", name: "Bulma", checked: false },
    { id: "foundation", name: "Foundation", checked: false },
  ],
  backendDevelopment: [
    { id: "node", name: "Node.js", checked: false },
    { id: "express", name: "Express", checked: false },
    { id: "nestjs", name: "NestJS", checked: false },
    { id: "django", name: "Django", checked: false },
    { id: "flask", name: "Flask", checked: false },
    { id: "laravel", name: "Laravel", checked: false },
    { id: "rails", name: "Ruby on Rails", checked: false },
    { id: "spring", name: "Spring Boot", checked: false },
    { id: "fastapi", name: "FastAPI", checked: false },
    { id: "asp", name: "ASP.NET", checked: false },
    { id: "grails", name: "Grails", checked: false },
  ],
  mobileAppDevelopment: [
    { id: "android", name: "Android", checked: false },
    { id: "ios", name: "iOS", checked: false },
    { id: "flutter", name: "Flutter", checked: false },
    { id: "reactnative", name: "React Native", checked: false },
    { id: "xamarin", name: "Xamarin", checked: false },
    { id: "ionic", name: "Ionic", checked: false },
    {
      id: "kotlinmultiplatform",
      name: "Kotlin Multiplatform",
      checked: false,
    },
    { id: "capacitor", name: "Capacitor", checked: false },
    { id: "cordova", name: "Cordova", checked: false },
  ],
  aiml: [
    { id: "tensorflow", name: "TensorFlow", checked: false },
    { id: "pytorch", name: "PyTorch", checked: false },
    { id: "scikitlearn", name: "Scikit-learn", checked: false },
    { id: "keras", name: "Keras", checked: false },
    { id: "opencv", name: "OpenCV", checked: false },
    { id: "huggingface", name: "Hugging Face", checked: false },
  ],
  database: [
    { id: "mongodb", name: "MongoDB", checked: false },
    { id: "postgresql", name: "PostgreSQL", checked: false },
    { id: "mysql", name: "MySQL", checked: false },
    { id: "sqlite", name: "SQLite", checked: false },
    { id: "redis", name: "Redis", checked: false },
    { id: "cassandra", name: "Cassandra", checked: false },
    { id: "dynamodb", name: "DynamoDB", checked: false },
    { id: "firebase", name: "Firebase", checked: false },
    { id: "elasticsearch", name: "Elasticsearch", checked: false },
    { id: "mariadb", name: "MariaDB", checked: false },
    { id: "couchdb", name: "CouchDB", checked: false },
    { id: "cockroachdb", name: "CockroachDB", checked: false },
    { id: "neo4j", name: "Neo4j", checked: false },
    { id: "oracle", name: "Oracle", checked: false },
  ],
  dataVisualization: [
    { id: "chartjs", name: "Chart.js", checked: false },
    { id: "tableau", name: "Tableau", checked: false },
    { id: "powerbi", name: "Power BI", checked: false },
    { id: "apacheairflow", name: "Apache Airflow", checked: false },
  ],
  devops: [
    { id: "kubernetes", name: "Kubernetes", checked: false },
    { id: "docker", name: "Docker", checked: false },
    { id: "jenkins", name: "Jenkins", checked: false },
    { id: "ansible", name: "Ansible", checked: false },
    { id: "terraform", name: "Terraform", checked: false },
    { id: "aws", name: "AWS", checked: false },
    { id: "gcp", name: "Google Cloud", checked: false },
    { id: "azure", name: "Azure", checked: false },
    { id: "heroku", name: "Heroku", checked: false },
    { id: "netlify", name: "Netlify", checked: false },
  ],
  baas: [
    { id: "supabase", name: "Supabase", checked: false },
    { id: "hasura", name: "Hasura", checked: false },
    { id: "parse", name: "Parse", checked: false },
  ],
  framework: [
    { id: "adonisjs", name: "AdonisJS", checked: false },
    { id: "codeigniter", name: "CodeIgniter", checked: false },
    { id: "cakephp", name: "CakePHP", checked: false },
    { id: "phalcon", name: "Phalcon", checked: false },
    { id: "dotnet", name: ".NET", checked: false },
    { id: "spring", name: "Spring", checked: false },
    { id: "play", name: "Play Framework", checked: false },
    { id: "sails", name: "Sails.js", checked: false },
    { id: "hapi", name: "Hapi.js", checked: false },
  ],
  testing: [
    { id: "cypress", name: "Cypress", checked: false },
    { id: "selenium", name: "Selenium", checked: false },
    { id: "jest", name: "Jest", checked: false },
    { id: "mocha", name: "Mocha", checked: false },
    { id: "jasmine", name: "Jasmine", checked: false },
    { id: "playwright", name: "Playwright", checked: false },
  ],
  software: [
    { id: "photoshop", name: "Photoshop", checked: false },
    { id: "illustrator", name: "Illustrator", checked: false },
    { id: "xd", name: "Adobe XD", checked: false },
    { id: "figma", name: "Figma", checked: false },
    { id: "blender", name: "Blender", checked: false },
    { id: "maya", name: "Maya", checked: false },
    { id: "3dsmax", name: "3ds Max", checked: false },
    { id: "aftereffects", name: "After Effects", checked: false },
  ],
  staticSiteGenerators: [
    { id: "gatsby", name: "Gatsby", checked: false },
    { id: "gridsome", name: "Gridsome", checked: false },
    { id: "hugo", name: "Hugo", checked: false },
    { id: "nextjs", name: "Next.js", checked: false },
    { id: "nuxtjs", name: "Nuxt.js", checked: false },
    { id: "eleventy", name: "Eleventy", checked: false },
    { id: "jekyll", name: "Jekyll", checked: false },
    { id: "hexo", name: "Hexo", checked: false },
    { id: "middleman", name: "Middleman", checked: false },
    { id: "scully", name: "Scully", checked: false },
    { id: "vuepress", name: "VuePress", checked: false },
    { id: "docusaurus", name: "Docusaurus", checked: false },
    { id: "zola", name: "Zola", checked: false },
  ],
  gameEngines: [
    { id: "unity", name: "Unity", checked: false },
    { id: "unreal", name: "Unreal Engine", checked: false },
  ],
  automation: [
    { id: "ifttt", name: "IFTTT", checked: false },
    { id: "zapier", name: "Zapier", checked: false },
  ],
  other: [
    { id: "linux", name: "Linux", checked: false },
    { id: "git", name: "Git", checked: false },
    { id: "npm", name: "NPM", checked: false },
  ],
};
